feat: add project demo
raxjs/awesome-rax pull request #3
Opened 2020-01-21 06:27 UTC by SoloJiang

1. Add vscode extention
2. Add project demo
3. Add storybook

2020-01-21 06:28 UTC, SoloJiang commented
样式有点问题

2020-02-26 03:00 UTC, ChrisCindy requested changes

2020-02-26 03:00 UTC, ChrisCindy commented on MINIAPP_PROJECT_DEMO.md
> +You can use Alipay scan these qr code.
You can use Alipay to scan these  QR codes.

2020-02-26 03:00 UTC, ChrisCindy commented on MINIAPP_PROJECT_DEMO.md
> +You can use Taobao scan these qr code.
You can use Taobao to scan these QR codes.

2020-02-26 03:07 UTC, ChrisCindy approved these changes

2020-02-26 03:14 UTC, merged